---
title: "Charactersing independent predictors in severe malaria"
output: html_notebook
---

# Background

This looks at the severe malaria legacy dataset from MORU

```{r, echo=FALSE}
load('RData/Data.R')
complete_cases = apply(m, 1, function(x) sum(is.na(x))) == 0
Leg_data = m[complete_cases,]
```


```{r}
# For the GAM modelling
library(mgcv)
# For the CART modelling
library(rpart)
library(rpart.plot)
```


# Full Model predicting death

```{r deathmodel}
mod_full = gam(outcome ~ s(HCT)+ s(AgeInYear) + BUN + BD + s(LPAR) + SYS_BP_NUMERIC + 
                  s(studyID, bs='re'),
                data=Leg_data, family=binomial)
```

Let's simulate all possible patients and compute their corresponding probability of death.

```{r}
All_patients = expand.grid(HCT=seq(4,45,by=2), 
                           BUN=seq(0,80,length.out = 10), 
                           BD=seq(-4,25, length.out = 15), 
                           SYS_BP_NUMERIC=0:1, 
                           LPAR=3:7, 
                           AgeInYear=c(1,2,3,4,5,10,20,50))
All_patients$studyID = Leg_data$studyID[1]
ys = 100*predict(mod_pars_0, newdata = All_patients, exclude="s(studyID)", type='response')
hist(ys, xlab='Probability of death', freq=F, yaxt='n', ylab='', main='')
abline(v=10, lwd=3, col='red')
```

We set a threshold mortality underneath which we term 'non-severe', above which is 'severe'.
```{r}
threshold = 5 # this is in percent
SeverityLabel = array(dim=length(ys))
SeverityLabel[ys>threshold] = 1
SeverityLabel[ys<= threshold] = 0
All_patients$SeverityLabel = SeverityLabel
plot(jitter(All_patients$HCT), jitter(All_patients$LPAR), col=SeverityLabel+1, pch='.')
```



# Direct effect of anaemia on death


```{r anaemiaEffect}
par(las=1)
plot(NA,NA, xlim=c(4,45), ylim=c(0,40),ylab='mortality', xlab='Haematocrit')
for(HCT in 4:45){
  mydata = Leg_data
  mydata$HCT=HCT
  ys = 100*predict(mod_full, newdata = mydata, exclude="s(studyID)", type='response')
  
  points(HCT,mean(ys), pch=18)
  points(rep(HCT,2), quantile(ys, probs=c(0.1,0.9)), pch='-', col='red')
}
```

